# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "__pycache__"
]

line-length = 100

[format]
# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
docstring-code-format = true
# Set the line length limit used when formatting code snippets in
# docstrings.
docstring-code-line-length = "dynamic"

[lint]
extend-select = [
    "A",
    "ANN",
    "ARG",
    "B",
    "C4",
    "C901",
    "D",
    "E",
    "F",
    "G",
    "I",
    "ICN",
    "PD",
    "PERF",
    "W",
    "RET",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "TCH",
    "TID"
]
extend-ignore = ["ANN101", "G004", "S311"]

[lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 5.
max-complexity = 7

[lint.pydocstyle]
convention = "google"

